on:
  push:
    branches-ignore:
    - master

name: CI
jobs:

  build-and-push:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build docker image
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: pablokbs/prueba-gha:${{ github.sha }}
        push: false
